name: Build-sphinx-doc

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-doc.txt
          pip install ghp-import

      - name: Build HTML
        run: |
          cd doc
          make html

      - name: Run ghp-import to generate GitHub Pages
        run: |
          ghp-import -npfo doc/_build/html